### ISSUE TITLE
Compliments where due

### ISSUE THREAD

**Issue by jakiestfu** [donovanh/zelda#1]
Just close this issue, I wish GitHub had a way to leave comments on a repo. Just wanted to say incredible work, your website bouncing animation is effing rad, and you've made a fan  out of me. Keep up the great work! :beers:

**Comment by donovanh** [comment]
Thanks Jacob! I really appreciate it. <img class="emoji" title=":beers:" alt=":beers:" src="https://a248.e.akamai.net/assets.github.com/images/icons/emoji/beers.png" height="20" width="20" align="absmiddle">
